on:
  workflow_call:
    inputs:
      configfile:
        required: true
        type: string
      runs_on:
        required: true
        type: string


jobs:
  release:
    runs-on: ${{ inputs.runs_on }}
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run release
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --rm-dist -f ${{ inputs.configfile }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
